[package]
name = "cfdi_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.36.1", features = ["serialize"] }
serde = {version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6.0"
chrono = "0.4"