[package]
name = "cfdi_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
minidom = "0.16"
quick-xml = { version = "0.37.0", features = ["serialize"] }
serde = {version = "1.0.215", features = ["derive"] }
serde-xml-rs = "0.6.0"
chrono = "0.4"
csv = "1.1"